ray job submit --address="http://127.0.0.1:8265" \
   -- python3 -m openrlhf.cli.train_ppo_ray \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 8 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 8 \
   --vllm_num_engines 4 \
   --vllm_tensor_parallel_size 2 \
   --colocate_all_models \
   --vllm_gpu_memory_utilization 0.7 \
   --num_episodes 3 \
   --pretrain ./outputs/deepscaler-1.5B-GRPO-stage_1 \
   --remote_rm_url /data/zju-46/xy/OpenRLHF/examples/scripts/reward_func_1_stage2.py \
   --save_path ./outputs/deepscaler-1.5B-GRPO-stage2-1 \
   --micro_train_batch_size 1 \
   --train_batch_size 128 \
   --micro_rollout_batch_size 8 \
   --rollout_batch_size 128 \
   --n_samples_per_prompt 8 \
   --max_epochs 1 \
   --prompt_max_len 1024 \
   --max_samples 10000 \
   --generate_max_len 2048 \
   --init_kl_coef 1e-4 \
   --gamma 1.0 \
   --use_kl_loss \
   --kl_estimator k3 \
   --advantage_estimator group_norm \
   --zero_stage 3 \
   --bf16 \
   --actor_learning_rate 1e-6 \
   --prompt_data parquet@../experiment/datasets/math_level3to5_data_processed_with_qwen_prompt/data \
   --input_key question \
   --label_key answer \
   --normalize_reward \
   --gradient_checkpointing \
   --packing_samples \
   --vllm_sync_backend nccl \
   --enforce_eager \
   --vllm_enable_sleep \
   --deepspeed_enable_sleep \
   --save_steps 100 \
   --ckpt_path ./outputs/deepscaler-1.5B-GRPO-stage2-1 \
   --use_tensorboard ./outputs/deepscaler-1.5B-GRPO-stage2-1